### ISSUE TITLE
Reliability errors? 

### ISSUE THREAD

**Issue by ghost** [CrosswaveOmega/NikkiBot#1]
Hey @CrosswaveOmega, 

Not sure if you're facing rate limit / server overloaded errors from OpenAI.. but if so, 

would recommend checking out `reliableGPT` - it'll handle the retries/switch models/gracefully fail for you 

```
from reliablegpt import reliableGPT
openai.ChatCompletion.create = reliableGPT(openai.ChatCompletion.create, ...)
```

Source: https://github.com/BerriAI/reliableGPT

**Comment by CrosswaveOmega** [comment]
I haven't been facing rate limit/server overloaded errors, but I'll be sure to keep this in mind.
